### ISSUE TITLE
Game Crashed While Selling Items.

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#93] opened 2022-10-15 08:46 UTC
The end of this video (Going live on the 17th or 18th) shows the bug: https://www.youtube.com/watch?v=_ODdaEWB988

Here is the error log:

2022-10-15 02:58:16.00
Version: 7.0.10
Exception: CONSTRAINT_ERROR
Message: Items.Inventory_Container.Constant_Reference: Index is out of range
-------------------------------------------------
raised CONSTRAINT_ERROR : Items.Inventory_Container.Constant_Reference: Index is out of range

-------------------------------------------------

**Comment by thindil** [comment] 2022-10-15 14:55
Hello, thank you for the report.

Unfortunately, the game didn't produce much information this time, so I will have to wait for the video. But I hope I will be able to fix it in this week. Also, the fix will be available for the next big stable version, which should be ready to download in two weeks.

Again, thank you for the report and I apologize for the problem.

**Comment by rmvgaines** [comment] 2022-10-17 18:13
The video should be up now.

**Comment by thindil** [comment] 2022-10-17 18:28
Yes, it is, thank you. I will try to reproduce the issue. Just the trade UI was redesigned in the new version of the game, and can happen that the bug will not occur there. I will post an update here in a few days.

Btw, I watched a few fragments of the video, and in my opinion it looks good. Thank you for your work there. 😄

**Comment by rmvgaines** [comment] 2022-10-18 07:12
Thank you for your work here! I'll look forwards to seeing the next update and will be sure to do a video update on it.

**Comment by thindil** [comment] 2022-10-18 15:15
Ok, small update from my side. 😉 I'm still trying to reproduce the issue. There are two opportunities: either I fixed it in the last several weeks in the development version (very unlikely) or I'm doing something wrong (more possible). And definitely I forgot one thing, to ask, do you still have the saved game on which the crash happened? If yes, could you, please, upload it here?

I will continue looking at it. Because, by the way, I found one more problem to fix. 😁

**Comment by rmvgaines** [comment] 2022-10-18 20:17
[saves.zip](https://github.com/thindil/steamsky/files/9814801/saves.zip)

There are always more bugs to find.

**Comment by thindil** [comment] 2022-10-19 06:14
Thank you again for your help. Now I know what I did wrong: the crash is always when trying to sell all the same items after sorting them. I should more carefully looking at the video. 😉 I will try to fix it for the 8.0 version. Temporary "workaround": don't sell all the same items after sorting them. I will also check other lists if they work correctly.

And bugs, yes, unfortunately. I really should learn how to write programs. 😆

**Comment by rmvgaines** [comment] 2022-10-19 06:28
I do have some other feedback on the UX in the video, but I am guessing that some of that is changing in the 8.0 release. If so, it would probably be wise for me to look at 8.0 before filing them as issues. If you want me to go ahead and file them now, I can do that.

**Comment by thindil** [comment] 2022-10-19 07:16
Yes, I think it is better to look around before giving a new feedback. Especially, the 8.0 version will bring almost only updates to the UI. But you don't need to wait, you can get the development version [7.9](https://github.com/thindil/steamsky/releases/tag/v7.9-dev) and check. Any feedback is welcome. And I hope that my ides also solve some of your problems with UI. 😉 Plus, I plan to continue to focus the work on the UI.

**Comment by thindil** [comment] 2022-10-22 04:48
Ok, I think this one should be fixed in the next stable version, 8.0 which should be released in the next Sunday. Again, thank you very much for the report, and I'm sorry for the problem.

**Closed by thindil** 2022-10-22 04:48 UTC
Labels: bug

**Comment by rmvgaines** [comment] 2022-10-22 18:52
No problem. I'll look forward to playing the latest release and will try to do a video update on it.
