### ISSUE TITLE
Open game settings crashes game in 5.7 and 5.8

### ISSUE THREAD

**Issue by ChrisEdBurt** [thindil/steamsky#73] opened 2021-02-25 02:02 UTC
When I attempt to open the game settings, it crashed the game.

Steps on how to reproduce the behavior:
1. Go to menu
2. Click on game settings
3 Game crashes.

[error.log](https://github.com/thindil/steamsky/files/6040061/error.log)

**Comment by thindil** [comment] 2021-02-25 05:24
Hello, thank you very much for the report and as usual, I'm sorry for the problem.
I will try to fix it in this week. The fixed version will be available in nightly releases in Actions (I will put here link too :smile: )

**Comment by ChrisEdBurt** [comment] 2021-02-25 07:38
Not a problem. 
It has been a while since I played, I was looking forward to seeing the new updates. 

A missing bracket is no biggie, I’m sure you’ll have it fixed in no time.

**Comment by thindil** [comment] 2021-02-25 09:25
I hope to fix it very soon :smile: As far I see, it is caused by Windows paths, the reason why it escaped me is that I test mainly on Linux. The only way to evade this crash will be updating the game to nightly build.

**Comment by thindil** [comment] 2021-02-27 05:45
And  I think that this bug should be fixed now :smile:. Thank you again for the report. 
You can download the nightly version with fix, from here: https://github.com/thindil/steamsky/actions/runs/604886502 (soon should be available) or any other later build. 
If you don't know how to use it, just ask (for example, here). On Windows it require only to download and unpack it over exiting the latest development version.

**Closed by thindil** 2021-02-27 05:45 UTC
Labels: bug

**Comment by ChrisEdBurt** [comment] 2021-02-27 09:27
That is excellent news!
I will check it once I have time, I’m looking forward to seeing the new stuff in the game.

**Comment by thindil** [comment] 2021-02-27 09:29
Thank you very much :smile: If you will still have this problem, feel free to reopen this issue or create new.
