### ISSUE TITLE
Scrolling cause the text to flicker

### ISSUE THREAD

**Issue by alkhimey** [thindil/steamsky#31] opened 2018-10-10 16:56 UTC
When a large box of text like help or messages is scrolled, it flickers:

I used the mouse scroll wheel here:

![peek 2018-10-10 19-50](https://user-images.githubusercontent.com/652603/46752669-7e56aa80-ccc6-11e8-846d-19f014e5257d.gif)

**Comment by thindil** [comment] 2018-10-10 18:00
Again hello and thanks for report ;)

Hmm, something new for me I been need to check it. Maybe something with UI animations. What happens when you disable them in options?

**Comment by alkhimey** [comment] 2018-10-10 18:20
I disabled the animations and no change.

![peek 2018-10-10 21-18](https://user-images.githubusercontent.com/652603/46757231-3ccbfc80-ccd2-11e8-9944-6a7bb28cb8c4.gif)

**Comment by thindil** [comment] 2018-10-10 20:34
Okies I will check it, thank you for help.

**Comment by thindil** [comment] 2018-10-11 11:51
Ok, I was tested everything on fresh install of Ubuntu 18.04 LTS (fully updated, minimal install). Everything works good for me (same with issues #32 and #34) - no flickering, darker (proper) colors, no white borders around buttons, etc. Maybe something was wrong during downloading? I mean some files may be corrupted. If this is not problem, could you please delete this version, download it again and check did everything works properly?

P.S. About issues #32 and #34  - probably they are caused by this same reason like this, thus I propose to talk only here. If problem will be fixed I'll close both after this too.

**Comment by thindil** [comment] 2018-10-12 08:10
Another option which can cause this problems is something wrong with setting GTKAda in `steamsky.sh` file. Thus i have few questions:
1. What is path to game? I mean literally something like this /a/b/c/gamehere.
2. How is game lauched? from terminal or file manager. 
3. From this same directory where `steamsky.sh` is or other?

**Comment by alkhimey** [comment] 2018-10-12 09:07
Hi,

I re downloaded the game as you suggested and run `steamsly.sh` and everything is working properly.
I suspect that previously I launched the executable in the `/bin` folder directly, and indeed all these issues are reproducible when doing this. So... I  aplogoise for wasting you time.

#31, #33, #34 are solved.
#32 is mostly solved. There are still some strange anomalies on the main menu and in various places (not many):
![peek 2018-10-12 11-58](https://user-images.githubusercontent.com/652603/46859731-3bf0b300-ce17-11e8-85d2-9545fdcea889.gif)

**Comment by thindil** [comment] 2018-10-12 09:33
No need to apologize, happens :) When I was trying to run binary directly it was simply crash for me, thus I even don't tested this option (and I should). Ok, I will add additional info to README.md too, maybe it help other people too when they been running game. And maybe some check to prevent run binary files directly on Linux.

Ok, then this (#31), #33 and #34 will be closed, #32 still to fix. As usual, thank you for your help and I'm sorry for all problems.

**Closed by thindil** 2018-10-12 09:33 UTC
Labels: bug, help wanted
