### ISSUE TITLE
Friendly trader

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#67] opened 2020-03-20 00:16 UTC
I am not sure at what triggers this one, but it seems:

Take a package mission, on the way to the destination meet a friendly trader, select "trade" and then the game sometimes crashes.

[error.log](https://github.com/thindil/steamsky/files/4357392/error.log)

**Comment by thindil** [comment] 2020-03-20 05:28
Hello and standard :) Thank you very much for the report I will try to look at it as soon as possible.

**Comment by thindil** [comment] 2020-03-23 05:31
This one also should be fixed, just I'm not sure - I can't reproduce this problem. Thank you for the report. If problem will be still exists, please reopen this issue or create new.

**Closed by thindil** 2020-03-23 05:31 UTC
Labels: bug, help wanted
